services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - user_service
      - room_service
      - booking_service

  user_service:
    build: ./user_service
    environment:
      - DB_HOST=db_user
      - DB_NAME=user_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db_user

  room_service:
    build: ./room_service
    environment:
      - DB_HOST=db_room
      - DB_NAME=room_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db_room

  booking_service:
    build: ./booking_service
    environment:
      - DB_HOST=db_booking
      - DB_NAME=booking_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db_booking
      - user_service
      - room_service

  db_user:
    image: postgres:13
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata_user:/var/lib/postgresql/data

  db_room:
    image: postgres:13
    environment:
      POSTGRES_DB: room_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata_room:/var/lib/postgresql/data

  db_booking:
    image: postgres:13
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata_booking:/var/lib/postgresql/data

volumes:
  pgdata_user:
  pgdata_room:
  pgdata_booking: